version: 2.1

executors:
  jdk11:
    working_directory: ~/formula-engine
    docker:
      - image: circleci/openjdk:11

jobs:
  build:
    executor: jdk11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn -Dtest.skipUnitTests=true install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - save_workspace
  test_unit:
    executor: jdk11
    steps:
      - load_workspace
      # To fail projects with no tests, add -Dcoverage.failIfNoTests=true
      - run: mvn verify 
      - save_unit_test_results
commands:
  save_workspace:
    description: Save current workspace
    steps:
      - persist_to_workspace:
          root: .
          paths: .
  load_workspace:
    description: Load workspace
    steps:
      - attach_workspace:
          at: ~/formula-engine
  save_unit_test_results:
    description: Saves unit test results to CircleCI
    steps:
      - run:
          name: Save unit test results
          command: |
            mkdir -p ~/test-results/unit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/unit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          name: Upload unit test artifacts
          path: ~/test-results/unit
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_unit:
          requires:
          - build
